# see https://github.com/travis-ci/travis-ci/issues/1528#issuecomment-184808978
sudo: required
dist: trusty

language: scala

scala:
  - 2.11.8
    
python:
  - 3.4

node_js:
  - 6.1

notifications:
  email: false

before_install:  # see http://stackoverflow.com/a/30496307/395386
    - sudo apt-get update
    - sudo apt-get install python3 python3-pip

install:
    - pip3 install --user -r clients/python/requirements.txt
    - npm install --prefix clients/javascript/ clients/javascript/

script:
    - pushd game && sbt clean test it:test && popd
    - pushd clients/python && python3 -m unittest discover -p "*_test.py" && popd
    - pushd clients/javascript && npm test && popd
