language: scala

scala:
  - 2.11.8

notifications:
  email: false

script:
    - pushd game && sbt clean test it:test && popd
    - pushd clients/python && python -m unittest discover -p "*_test.py" && popd
