language: scala

scala:
  - 2.11.8

notifications:
  email: false

before_install:  # see http://stackoverflow.com/a/30496307/395386
    - sudo apt-get update
    - sudo apt-get install python3 python3-pip

install: pip3 install -r clients/python/requirements.txt

script:
    - pushd game && sbt clean test it:test && popd
    - pushd clients/python && python3 -m unittest discover -p "*_test.py" && popd
