version: '3'

volumes:
  database_data:
    driver: local
  web_data:

services:
  web:
    build: ./web/
    volumes:
      - ./web/src/:/src/src/
      - ./web/package.json:/src/package.json
      - ./web/gulpfile.js:/src/gulpfile.js
      - ./web/webpack.config.js:/src/webpack.config.js
      - ./web/dist/:/src/dist/
    command: [npm, run, watch]

  game:
    build: ./game/
    volumes:
      - ./game/project/:/game/project/
      - ./game/src/:/game/src/
      - ./game/target/:/game/target/
