version: '2'

volumes:
  database_data:
    driver: local

services:
  api:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./api/nginx.docker.conf:/etc/nginx/nginx.conf
      - ./api/mime_types:/etc/nginx/mime_types
      - ./api/logs/:/etc/nginx/logs/
    volumes_from:
      - web:ro

  web:
    build: ./web/
    volumes:
      - ./web/src/:/src/src/
      - ./web/package.json:/src/package.json
      - ./web/gulpfile.js:/src/gulpfile.js
      - ./web/webpack.config.js:/src/webpack.config.js
      - ./web/dist/:/src/dist/
    command: [npm, run, watch]
