version: '3'

volumes:
  database_data:
    driver: local
  web_data:

services:
  api:
    image: funkygibbon/nginx-pagespeed
    environment:
      - APP_HOSTNAME=default
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./api/sites-enabled/:/etc/nginx/sites-enabled/
      - ./api/mime_types:/etc/nginx/mime_types
      - ./api/logs/:/etc/nginx/logs/
      - web_data:/src/dist/
    links:
      - "game:game"

  web:
    image: drpandemic/aigario-web-dev
    volumes:
      - ./web/src/:/src/src/
      - ./web/package.json:/src/package.json
      - ./web/gulpfile.js:/src/gulpfile.js
      - ./web/webpack.config.js:/src/webpack.config.js
      - web_data:/src/dist/
    command: [npm, run, watch]

  game:
    build: ./game/
    expose:
      - 8080
    ports:
      - 1090:1090
    volumes:
      - ./game/project/:/game/project/
      - ./game/src/:/game/src/
      - ./game/target/:/game/target/
    command: [sbt, "~;jetty:stop;jetty:start"]
