version: '2'

volumes:
  database_data:
    driver: local

services:
  api:
    image: nginx:alpine
    ports:
      - 1337:80
    volumes:
      - ./api/nginx.docker.conf:/etc/nginx/nginx.conf
      - ./api/mime_types:/etc/nginx/mime_types
      - ./api/docker-logs/:/etc/nginx/logs/
    volumes_from:
      - web:ro
    links:
      - "game:game"

  web:
    build: ./web/
    volumes:
      - ./web/src/:/src/src/
      - ./web/package.json:/src/package.json
      - ./web/gulpfile.js:/src/gulpfile.js
      - ./web/webpack.config.js:/src/webpack.config.js
      - ./web/docker-dist/:/src/dist/
    command: [npm, run, watch]

  game:
    build: ./game/
    expose:
      - 8080
    volumes:
      - ./game/project/:/game/project/
      - ./game/src/:/game/src/
    command: [sbt, "~;jetty:stop;jetty:start"]
